version: '3.8'

services:
  mysql:
    image: mysql:5.6
    platform: linux/amd64
    container_name: scheduler-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scheduler
      MYSQL_USER: tester
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - stt_network

volumes:
  mysql_data:
    driver: local

networks:
  stt_network:
    driver: bridge